steps:
  - command: "echo hello world"
    env:
      OMP_NUM_THREADS: 0
      NUM_HYPERTHREADS: 0
    plugins:
      - https://github.com/buildkite/slurm-buildkite-plugin:
          time: "00:05:00"
          nodes: 1
          ntasks-per-node: 16
          modules:
            - "fftw-xl/3.3.4"
            - "vlsci"
